# Generated by Django 4.2.3 on 2023-07-31 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0002_category_note_notesharinginvitation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_notes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
