# Generated by Django 4.2.3 on 2023-07-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_note_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.AddField(
            model_name="note",
            name="categories",
            field=models.ManyToManyField(blank=True, to="notes.category"),
        ),
    ]
